name: PunishBroadcast
version: 1.0
main: com.perceivedev.punishbroadcast.PunishBroadcast
description: A simple broadcaster for punish commands
commands:
    punishbroadcast:
        description: "Management command for PunishBroadcast"
        aliases: [pb]
        usage: "\u00a7cSomething went wrong!"
